-- Supabase SQL Editor: выполните этот скрипт в новом проекте.
-- Это стартовая схема для бесплатного Supabase-плана.

create table if not exists employees (
  id bigint primary key,
  telegram_id bigint unique,
  name text not null,
  username text,
  role text not null default 'actor',
  is_active boolean not null default true,
  efficiency int not null default 0,
  accepted int not null default 0,
  late int not null default 0,
  rating numeric not null default 0
);

create table if not exists programs (
  id bigint generated by default as identity primary key,
  title text not null,
  age text,
  duration text,
  drive_url text,
  price_per_hour int not null default 0,
  actor_pay_per_hour int not null default 0,
  tracks jsonb not null default '[]'::jsonb
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  title text not null,
  date text not null,
  time text not null,
  address text,
  role text,
  actors jsonb not null default '[]'::jsonb,
  status text not null default 'Новый',
  kit_status text not null default 'Комплект не взят',
  available text not null default ''
);

create table if not exists props (
  id bigint generated by default as identity primary key,
  name text not null,
  status text not null default 'available',
  place text,
  kit boolean not null default false
);

create table if not exists accepted_orders (
  order_id bigint primary key references orders(id) on delete cascade,
  actor_id bigint not null,
  name text not null,
  accepted_at timestamptz not null default now()
);

create table if not exists actions (
  id bigint primary key,
  type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  status text not null default 'received'
);

create table if not exists reports (
  id bigint generated by default as identity primary key,
  actor_id bigint,
  text text not null,
  route text,
  created_at timestamptz not null default now()
);

insert into employees (id, telegram_id, name, username, role, efficiency, accepted, late, rating)
values
  (101, 101, 'Даша', 'dasha_actor', 'actor', 86, 12, 1, 4.8),
  (102, 102, 'Илья', 'ilya_actor', 'actor', 74, 8, 2, 4.4),
  (103, 103, 'Маша', 'masha_actor', 'actor', 92, 16, 0, 4.9)
on conflict (id) do nothing;

insert into programs (title, age, duration, price_per_hour, actor_pay_per_hour, tracks)
values
  ('Челлендж Пати Влада А4', '7-12 лет', '120 минут', 4500, 1600, '["Выход ведущего", "Конкурс 1", "Финал"]'),
  ('Крио-шоу', '5-12 лет', '60 минут', 6200, 1900, '["Старт шоу", "Эксперимент", "Финал"]')
on conflict do nothing;
